/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MessageVaultInterface extends Interface {
  getFunction(nameOrSignature: "recordMessage"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MessageRecorded"): EventFragment;

  encodeFunctionData(
    functionFragment: "recordMessage",
    values: [AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "recordMessage",
    data: BytesLike
  ): Result;
}

export namespace MessageRecordedEvent {
  export type InputTuple = [
    sender: AddressLike,
    recipient: AddressLike,
    cid: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    recipient: string,
    cid: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    sender: string;
    recipient: string;
    cid: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MessageVault extends BaseContract {
  connect(runner?: ContractRunner | null): MessageVault;
  waitForDeployment(): Promise<this>;

  interface: MessageVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  recordMessage: TypedContractMethod<
    [recipient: AddressLike, cid: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "recordMessage"
  ): TypedContractMethod<
    [recipient: AddressLike, cid: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MessageRecorded"
  ): TypedContractEvent<
    MessageRecordedEvent.InputTuple,
    MessageRecordedEvent.OutputTuple,
    MessageRecordedEvent.OutputObject
  >;

  filters: {
    "MessageRecorded(address,address,string,uint256)": TypedContractEvent<
      MessageRecordedEvent.InputTuple,
      MessageRecordedEvent.OutputTuple,
      MessageRecordedEvent.OutputObject
    >;
    MessageRecorded: TypedContractEvent<
      MessageRecordedEvent.InputTuple,
      MessageRecordedEvent.OutputTuple,
      MessageRecordedEvent.OutputObject
    >;
  };
}
